#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="bash curl python python-xml shadow sudo systemd vim wget which"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}/leap:${image_tag})

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}

# Volume definitions
buildah config --volume /sys/fs/cgroup ${container}
buildah config --volume /run ${container}

# Provision the container
buildah run ${container} zypper -n in ${packages}
buildah run ${container} zypper clean

# Fix https://github.com/jam82/buildah-molecule-images/issues/3
# Fix High CPU usage on zombie `agetty` processes when using with `molecule` #9
# see https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/9
buildah run ${container} rm -f /usr/lib/systemd/system/systemd*udev*
buildah run ${container} rm -f /usr/lib/systemd/system/getty.target
buildah run ${container} rm -f /usr/lib/systemd/system/dev-hugepages.mount
buildah run ${container} rm -f /usr/lib/systemd/system/proc-sys-fs-binfmt_misc.automount
buildah run ${container} rm -f /usr/lib/systemd/system/sysinit.target.wants/proc-sys-fs-binfmt_misc.automount
buildah run ${container} rm -f /usr/lib/systemd/system/systemd-remount-fs.service
buildah run ${container} rm -f /usr/lib/systemd/system/systemd-sysctl.service
buildah run ${container} rm -f /usr/lib/systemd/system/systemd-tmpfiles-setup.service

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /usr/lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --squash ${container} ${image_name}:${image_tag}
