#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="bash findutils iproute2 python python-xml shadow sudo systemd"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}/tumbleweed:latest)

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}

# Provision the container
buildah run ${container} zypper -n update
buildah run ${container} zypper -n in ${packages}
buildah run ${container} zypper clean

# Fix https://github.com/jam82/buildah-molecule-images/issues/3
# adopted from https://github.com/bdellegrazie/docker-debian-systemd/
buildah run ${container} find /etc/systemd/system /usr//lib/systemd/system \
    -path 'sysinit.target.wants/*' -not -name '*systemd-tmpfiles*' -delete

buildah run ${container} rm -f /usr/lib/systemd/system/multi-user.target.wants/*
buildah run ${container} rm -f /etc/systemd/system/*.wants/*
buildah run ${container} rm -f /usr/lib/systemd/system/local-fs.target.wants/*
buildah run ${container} rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*
buildah run ${container} rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*
buildah run ${container} rm -f /usr/lib/systemd/system/basic.target.wants/*

buildah run ${container} systemctl mask getty.service

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /usr/lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --rm ${container} ${maintainer}/${repo_name}:${image_tag}
