#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="bash curl python shadow sudo systemd \
    vim wget which"

# Create a container
container=$(buildah from ${image_name}/tumbleweed:latest)

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}

# Volume definitions
buildah config --volume /sys/fs/cgroup ${container}

# Provision the container
buildah run ${container} zypper -n in ${packages}
buildah run ${container} zypper clean

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /usr/lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --squash ${container} ${image_name}:${image_tag}

# Lookup credentials via secret-tool and push image to docker registry
buildah push --creds \
    ${registry_user}:$(secret-tool lookup docker hub user ${registry_user}) \
    localhost/${image_name}:${image_tag} \
    docker://${registry_user}/molecule-${image_name}:${image_tag}