#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="awk bash curl dbus grep procps-ng python3 sed sudo \
    systemd-sysvcompat vim wget which"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}:base)

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}

# Volume definitions
buildah config --volume /run ${container}
buildah config --volume /run/lock ${container}
buildah config --volume /sys/fs/cgroup ${container}
buildah config --volume /sys/fs/fuse ${container}
buildah config --volume /tmp ${container}
buildah config --volume /var/lib/journal ${container}

# Provision the container
buildah run ${container} pacman -Syyu --noconfirm
buildah run ${container} pacman -S --noconfirm ${packages}
buildah run ${container} pacman -Scc --noconfirm
buildah run ${container} rm -rf /usr/share/doc/*
buildah run ${container} rm -rf /usr/share/man/*
buildah run ${container} rm -rf /var/lib/apt/lists/*
buildah run ${container} rm -rf /tmp/*
buildah run ${container} rm -rf /var/tmp/*

# Fix https://github.com/jam82/buildah-molecule-images/issues/3
# adopted from https://github.com/bdellegrazie/docker-debian-systemd/
buildah run ${container} find /etc/systemd/system /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*dbus*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -delete

buildah run ${container} systemctl set-default sysinit.target

buildah run ${container} systemctl mask \
    dev-hugepages.mount \
    getty.service \
    proc-sys-fs-binfmt_misc.automount \
    sys-fs-fuse-connections.mount \
    systemd-journald-audit.socket \
    systemd-tmpfiles-setup.service \
    systemd-udev-trigger.service

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /usr/lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --squash ${container} ${image_name}:${image_tag}
