#!/usr/bin/env bash

set -o errexit

source ./images/common

clean() {
	buildah unshare podman images --format "{{.ID}}" \
	--filter label=maintainer="${maintainer}" \
	| xargs -r podman rmi -f
}

clean_unused() {
	podman image prune -af
}

clean_all() {
	podman rmi -af
}

log_action "Started cleaning up ${1:-"own"} images ..."

if [ -z ${1} ]; then
	clean
elif [ ${1} == "all" ]; then
	clean_all
else
	clean_unused
fi

log_action "Finished cleaning up ${1:-"own"} images ..."
