#!/usr/bin/env bash

declare -a containers
declare -a paths
declare -a service_manager

declare -r maintainer="Jonas Mauer <jam@kabelmail.net"
declare -r registry_user="jam82"

fill_arrays() {
    containers=$(\
        for path in $@; \
        do \
            echo $path | cut -d '/' -f3,4 | sed 's/\//:/'; \
        done \
    )
    paths=$@
}

if [ -z $1 ]; then
    fill_arrays $(find ./images -mindepth 2 -type f 2>/dev/null || echo "")
else
    fill_arrays $(find ./images/$1 -type f 2>/dev/null | echo "")
fi
