#!/usr/bin/env bash

set -o errexit

declare -a containers
declare -a paths

declare -r maintainer="jam82"

if [ -z ${DOCKER_REGISTRY_SECRET} ]; then
    DOCKER_REGISTRY_SECRET="$(secret-tool lookup docker hub user ${maintainer})"
fi

fill_arrays() {
    containers=$(\
        for path in $@; \
        do \
            echo $path | cut -d '/' -f3,4 | sed 's/\//:/'; \
        done \
    )
    paths=$@
}

if [ -z $1 ]; then
    fill_arrays $(find ./images -mindepth 2 -type f 2>/dev/null || echo "")
else
    fill_arrays $(find ./images/$1 -type f 2>/dev/null | echo "")
fi
