#!/usr/bin/env bash

set -o errexit

source ./images/common

log_action "Starting build run ..."

find ./images/$@/ -mindepth 1 -maxdepth 1 -type f \
    -exec echo -e "${green}Launching {} ...${end}" \; \
    -exec {} \;

# for travis
if [ $? == 0 ]; then
    log_action "Finished build run."
else
    exit 1
fi
