#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="apt-utils bash ca-certificates dh-systemd grep iproute2 locales \
    python python-apt rsyslog sudo systemd systemd-sysv \
    vim-tiny wget"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}:${image_tag})

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}
buildah config --env LC_ALL=C ${container}
buildah config --env DEBIAN_FRONTEND=noninteractive ${container}

# Volume definitions
buildah config --volume /sys/fs/cgroup ${container}

# Provision the container
buildah run ${container} apt-get update
buildah run ${container} apt-get -y dist-upgrade
buildah run ${container} apt-get install -y ${packages}
buildah run ${container} apt-get clean
buildah run ${container} rm -Rf /usr/share/doc 
buildah run ${container} rm -Rf /usr/share/man
buildah run ${container} rm -Rf /var/lib/apt/lists/*
buildah run ${container} sed -i 's/^\($ModLoad imklog\)/# \1/' /etc/rsyslog.conf
buildah run ${container} locale-gen en_US.UTF-8
buildah run ${container} locale-gen de_DE.UTF-8

# Fix High CPU usage on zombie `agetty` processes when using with `molecule` #9
# https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/9
buildah run ${container} rm -f /lib/systemd/system/systemd*udev*
buildah run ${container} rm -f /lib/systemd/system/getty.target

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --squash ${container} ${image_name}:${image_tag}
