#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="apt-utils bash ca-certificates curl grep iproute2 locales \
    python3 python3-apt rsyslog sudo systemd systemd-sysv \
    vim wget"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}:${image_tag})

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}
buildah config --env LC_ALL=C ${container}
buildah config --env DEBIAN_FRONTEND=noninteractive ${container}

# Provision the container
buildah run ${container} apt-get update
buildah run ${container} apt-get -y dist-upgrade
buildah run ${container} apt-get install -y ${packages}
buildah run ${container} apt-get clean
buildah run ${container} sed -i 's/^\($ModLoad imklog\)/# \1/' /etc/rsyslog.conf
buildah run ${container} locale-gen en_US.UTF-8
buildah run ${container} locale-gen de_DE.UTF-8
buildah run ${container} rm -rf /usr/share/doc/*
buildah run ${container} rm -rf /usr/share/man/*
buildah run ${container} rm -rf /var/lib/apt/lists/*
buildah run ${container} rm -rf /tmp/*
buildah run ${container} rm -rf /var/tmp/*

# Fix https://github.com/jam82/buildah-molecule-images/issues/3
# adopted from https://github.com/bdellegrazie/docker-debian-systemd/
buildah run ${container} find /etc/systemd/system /lib/systemd/system \
    -path '*.wants/*' \
    -not -name '*dbus*' \
    -not -name '*journald*' \
    -not -name '*systemd-tmpfiles*' \
    -not -name '*systemd-user-sessions*' \
    -delete

buildah run ${container} systemctl set-default sysinit.target

buildah run ${container} systemctl mask \
    dev-hugepages.mount \
    sys-fs-fuse-connections.mount

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --squash ${container} ${image_name}:${image_tag}
