#!/usr/bin/env bash

set -o errexit

# Get scripts parent path and change into it (if running from Makefile)
parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "${parent_path}"

# source common settings
source ../common

# Define container name, tag and repository name
image_name=${PWD##*/}
image_tag=$(basename "$0")
repo_name="molecule-${image_name}"

# Define packages to be installed
packages="apt-utils bash ca-certificates grep iproute2 \
    python3 python3-apt sudo systemd systemd-sysv"

# Create a container
container=$(buildah from --format=docker ${default_registry}/${image_name}:${image_tag})

# Label the container
buildah config --label maintainer="${maintainer}" ${container}

# Set environment variables
buildah config --env container=docker ${container}
buildah config --env LC_ALL=C ${container}
buildah config --env DEBIAN_FRONTEND=noninteractive ${container}

# Provision the container
buildah run ${container} apt update
buildah run ${container} apt -y full-upgrade
buildah run ${container} apt install -y ${packages}
buildah run ${container} apt clean

# Fix https://github.com/jam82/buildah-molecule-images/issues/3
# adopted from https://github.com/bdellegrazie/docker-debian-systemd/
buildah run ${container} find /etc/systemd/system /lib/systemd/system \
    -path 'sysinit.target.wants/*' -not -name '*systemd-tmpfiles*' -delete

buildah run ${container} rm -f /lib/systemd/system/multi-user.target.wants/* ; \
buildah run ${container} rm -f /etc/systemd/system/*.wants/* ; \
buildah run ${container} rm -f /lib/systemd/system/local-fs.target.wants/* ; \
buildah run ${container} rm -f /lib/systemd/system/sockets.target.wants/*udev* ; \
buildah run ${container} rm -f /lib/systemd/system/sockets.target.wants/*initctl* ; \
buildah run ${container} rm -f /lib/systemd/system/basic.target.wants/* ; \
buildah run ${container} rm -f /lib/systemd/system/anaconda.target.wants/* ; \
buildah run ${container} rm -f /lib/systemd/system/plymouth* ; \
buildah run ${container} rm -f /lib/systemd/system/systemd-update-utmp*

# Fix High CPU usage on zombie `agetty` processes when using with `molecule` #9
# https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/9
buildah run ${container} rm -f /lib/systemd/system/systemd*udev*
buildah run ${container} rm -f /lib/systemd/system/getty.target

buildah run ${container} systemctl mask getty.service

# Do not require tty on ssh connection (to speed up ansible)
buildah run ${container} sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/' \
    /etc/sudoers

# CMD to run when starting container
buildah config --cmd /lib/systemd/systemd ${container}

# Save running container to image and squash all layers to one
buildah commit --format docker --rm ${container} ${maintainer}/${repo_name}:${image_tag}
